name: Bug Report
description: Create a bug report for the Deforum fork for Forge
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: what-did
    attributes:
      label: What happened and why was it ungood?
      description: Tell us what didn't go the way you expected.
    validations:
      required: true
